language: node_js
node_js:
  - "14.16.0"
services:
  - mongodb
  - redis-server
before_script:
  - npm install
script: 
  - npm test
  - npm run coveralls
  - npm run coverage
# after_script:
#   - npm run coverage
#   - npm run coveralls
notifications:
  email: true