language: node_js
node_js:
  - "14.16.0"
services:
  - mongodb
  # - redis-server
# before_install:
#   - sudo apt-get install -y mongodb-org
before_script:
  - npm install
  # - sleep 30
  # - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  # - npm test
script: 
  - npm test
  - npm run coverage
  - npm run coveralls
# after_script:
#   - npm run coverage
#   - npm run coveralls
notifications:
  email: true