language: node_js
node_js:
  - "14.16.0"
services:
  - mongodb
  # - redis-server
before_script:
  - npm install
  - sleep 20
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script: 
  - npm test
after_script:
  - npm run coverage
  - npm run coveralls
notifications:
  email: true