version: "3.8"

services:
  e-commerce:
    restart: always
    depends_on:
      - redis
      - mongo
    build: .
    ports:
      # - 127.0.0.1:3000:3000
      - 3000:3000
    env_file: .env
    # environment:
    #   CONNECTIONSTRING: mongodb://mongo:27017/${DATABASE}
    #   DATABASE: ${DATABASE}
    #   JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    #   ADMIN: ${ADMIN}
    #   TEST_DATABASE: ${TEST_DATABASE}
    #   PAYSTACK_TEST_SECRET_KEY: ${PAYSTACK_TEST_SECRET_KEY}
    #   PAYSTACK_TEST_SECRET_KEY_TEST: ${PAYSTACK_TEST_SECRET_KEY_TEST}
    #   GMAIL: ${GMAIL}
    #   GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    #   TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
    #   TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
    volumes:
      - ./:/app

  redis:
    image: redis:6-alpine
    # command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  mongo:
    image: mongo:4.2.8
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
